{% set name = "pidibble" %}
{% set version = "1.0.7.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pidibble-{{ version }}.tar.gz
  sha256: 30251cb5fdead24583e2f9c52da06583e6d9a3f1372ccb0f7f0c3cd372469c6d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
  run:
    - python >=3.7
    - numpy >=1.24
    - pyyaml >=6

test:
  imports:
    - pidibble
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A complete Protein Data Bank (PDB) file parser
  home: https://github.com/cameronabrams/pidibble
  dev_url: https://github.com/cameronabrams/pidibble
  doc_url: https://pidibble.readthedocs.io/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cameronabrams
