{% set name = "pidibble" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pidibble-{{ version }}.tar.gz
  sha256: 7f5013a0a412a569ee77424e0ccb2aaf61abea1f9316d735e438736737f5471d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
  run:
    - python >=3.7
    - numpy >=1.24
    - pyyaml >=6

test:
  imports:
    - pidibble
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A complete Protein Data Bank (PDB) file parser
  home: https://github.com/cameronabrams/pidibble
  dev_url: https://github.com/cameronabrams/pidibble
  doc_url: https://pidibble.readthedocs.io/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cameronabrams
